version: '3'

services:
  gravity:
    image: onomy/gravity-bridge-single-node-runner:local
    restart: on-failure
    container_name: gravity-bridge-single-node-runner
    ports:
      # gravity
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 61278:61278
      - 9090:9090
      # ethereum
      - 8545:8545