version: '3'

services:
  gravity:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      # gravity
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 61278:61278
      - 9090:9090
      # ethereum
      - 8545:8545