version: '3'

services:
  gravity:
    image: onomy/gravity-bridge-single-node-runner-rinkeby:local
    restart: on-failure
    container_name: gravity-bridge-single-node-runner-rinkeby
    volumes:
      - ./scripts:/root/home/scripts
      - ./gravity_home :/root/home/testchain/gravity/.
    ports:
      # gravity
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 61278:61278
      - 9090:9090
      # ethereum
      - 8545:8545