name: Cosmos Master Node
on: [ push, pull_request ]


jobs:
  amd64:
    name: Cosmos Master
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push blockchain
        run: docker buildx build --tag leeway321/cosmos-master-node --file module/cosmosNode/master/Dockerfile --platform linux/amd64 --cache-from leeway321/cosmos-master-node:cache --cache-to leeway321/cosmos-master-node:cache --push --progress tty --build-arg ip_address=167.99.153.118 .
