name: SSH-ACTION
on: [push, pull_request]

jobs:
  amd64:
    name: SSH-ACTION
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ONET-44'
    steps:
      - name: start full node
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: bash -c ls | ls | touch test| mkdir testy | mv test /testy
          host: ${{ secrets.HOST }}
          username: root
          password: ""
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
