name: SSH-ACTION
on: [push, pull_request]

jobs:
  amd64:
    name: SSH-ACTION
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ONET-44'
    steps:
      - name: Commands via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: bash run.sh
          host: ${{ secrets.HOST }}
          username: root
          password: ""
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
