name: SSH-ACTION
on: [push, pull_request]

jobs:
  amd64:
    name: SSH-ACTION
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ONET-44'
    steps:
      - name: clone gravity-bridge folder in machine
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: git clone -b ONET-44 https://github.com/shivaLeeway/gravity-bridge
          host: ${{ secrets.HOST }}
          username: root
          password: ""
          privateKey: ${{ secrets.PRIVATE_KEY}}
      - name: Run run.sh file
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: bash gravity-bridge/module/ssh/run.sh
          host: ${{ secrets.HOST }}
          username: root
          password: ""
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
